### ISSUE TITLE
Allow SASS/SCSS compiling

### ISSUE THREAD

**Issue by sssoz** [oaworks/oa-works#1]
https://dev.to/mathieuhuot/processing-sass-with-11ty-5a09
https://www.belter.io/eleventy-sass-workflow/ 

--- 

TODO

- [x] Finish Gulp SCSS setup! 
- [x] Move all static asset directories and files to the structure shown above (JS, favicons, fonts, img)
- [x] Fix up URL paths in templates (they’ll be probably a bit everywhere, might need to Regex that), ensure all of these static files still work, and test them visually
- [x] Rename all `.css` files to be `.scss` partials prefixed with `_` — i.e. `homepage.css` becomes `_homepage.scss`_
- [x] Create `main.scss` in the new `css/`directory 
- [x] Basing yourself on the structure and order of the current `main.html` (found in `oa-works/src/`), import all individual `scss` in that `main.scss`file using the `@import` rule

**Comment by thinkbulecount2** [comment]
Just created a [branch](https://github.com/oaworks/oa-works/tree/setup-sass) where I installed node-sass (will add documentation) to package.json, converted the existing CSS into SCSS, then ran `npm run scss` to compile the SCSS files back into CSS. I've taken a look around running it locally with the changes and I don't think there's an issue with any misplaced CSS during the compiling — do let me know if you are able to see, @sssoz! Otherwise, I'll be sending a PR your way. :)

**Comment by sssoz** [comment]
Added the list as TODOs in original comment.

**Comment by thinkbulecount2** [comment]
Just some additional notes from the above TODO

- [x]  Rename all .css files to be .scss partials prefixed with _ — i.e. homepage.css becomes _homepage.scss_
- [x]  Create main.scss in the new css/directory
- [x]  Basing yourself on the structure and order of the current main.html (found in oa-works/src/), import all individual scss in that main.scssfile using the @import rule
_@import has been deprecated; SASS recommends using @use instead_

**Comment by thinkbulecount2** [comment]
TODO

- [x]  Finish Gulp SCSS setup!
- [x]  Move all static asset directories and files to the structure shown above (JS, favicons, fonts, img)
- [x]  Fix up URL paths in templates (they’ll be probably a bit everywhere, might need to Regex that), ensure all of these static files still work, and test them visually
- [x]  Rename all .css files to be .scss partials prefixed with _ — i.e. homepage.css becomes _homepage.scss_
- [x]  Create main.scss in the new css/directory
- [x]  Basing yourself on the structure and order of the current main.html (found in oa-works/src/), import all individual scss in that main.scssfile using the @import rule
- [ ]  Test that all CSS output still works. Ghost Inspector might come in handy with this — we can do this together on our next call
_Saving this last one so we can look at it together @sssoz!_

**Comment by thinkbulecount2** [comment]
Additional tasks:

- [ ] Write documentation

**Comment by sssoz** [comment]
@thinkbulecount2 Just checking in on this task. When we spoke on Friday, you mentioned wanting to finish this up (or finishing the a11y issues). Are there any updates on either?

**Comment by thinkbulecount2** [comment]
I'm just adding in some documentation for this and then pushing (with instructions on how to deploy on Netlify) -- the a11y I will be finishing up EOD tomorrow.

**Comment by thinkbulecount2** [comment]
Hi @sssoz, something came up yesterday so will push today and do a11y Wednesday. Sorry for the trouble!

**Comment by sssoz** [comment]
@thinkbulecount2 No problem; do leave an update if possible.

**Comment by sssoz** [comment]
@thinkbulecount2 I’ll let you close this one :)

**Comment by thinkbulecount2** [comment]
⭐️✨😊
