### ISSUE TITLE
Add Ashley’s testimonial

### ISSUE THREAD

**Issue by sssoz** [oaworks/oa-works#115]
https://docs.google.com/document/d/121Nl2ofca-Boy_uwJ5NgigEtP8fWE3ok7Ije6f2kUQQ/edit?usp=sharing

**Comment by sssoz** [comment]
@JosephMcArthur Done and on dev, feel free to close when we make the announcement

**Comment by sssoz** [comment]
Also let me know when I can merge with main

**Comment by JosephMcArthur** [comment]
Whenever :) thanks!

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur

**Comment by sssoz** [comment]
That was released a few hours ago already, like we discussed on chat when you made the announcement..
