### ISSUE TITLE
three dots sometimes, not other times

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/oa-works#116]
On some pages, e.g https://dev.oa.works/about/ there are the three dots

![image](https://user-images.githubusercontent.com/4953703/125951864-ea65dd3f-6f4b-4a07-99cc-0ad8a69783bd.png)

on others, e.g https://dev.oa.works/impact/ there are no dots

Perhaps simply my memory is failing me, but, I thought the intent was to have the dots on all pages (except some obvious ones, like the homepage). I know you asked for testing during housekeeping but I wasn't able to look then but noticed now.

If things as they are is your intent, that's a-okay and I have no problem with it. If it isn't, then here's an FYI :)

**Comment by sssoz** [comment]
Should only happen when there is no meta description text input for that page

**Comment by JosephMcArthur** [comment]
Joe needs to review / add intro text if desired on these pages

**Comment by JosephMcArthur** [comment]
Just did a quick review –– no major issues I see. Things could probably be better, but that's not a priority and so if this isn't a bug then it can be closed.
