### ISSUE TITLE
On ultra-wide screens sites have layout bugs

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/oa-works#117]
A gif showing what I mean: https://recordit.co/2GVIrKjUhk. I attempt to circle with my mouse but I'm not sure it's that noticeable. Basically, some elements don't quite reaching the edges, but others do, and that causes some odd outcomes.

I think we have discussed how few users have screens as wide / tall as mine –– so this isn't a priority. However, thought I'd flag as I'm often showing / testing things and occasionally I hit odd issues that turn out to not actually be issues for most people. Generally speaking, I just discount / remember these issues and don't demonstrate in full full screen. But, if after housekeeping this is a trivial thing to address then perhaps it's worthwhile. Otherwise, it's fine to shut / consider "wontfix".

@sssoz, totally your call as to where to prioritize within your work.

**Comment by sssoz** [comment]
Think we need to review the grid better.

**Comment by sssoz** [comment]
@JosephMcArthur  I think I might have fixed it by doing something else, can you check on https://oa.works/ ?

**Comment by JosephMcArthur** [comment]
Looks good on live. On dev it's as is.

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur

**Comment by sssoz** [comment]
Dev isn’t synced to main right now, I just pushed it directly to live!

**Comment by sssoz** [comment]
@JosephMcArthur Can you check to see if this works now on your screen and close it?

**Comment by JosephMcArthur** [comment]
Still looks great, thanks!
