### ISSUE TITLE
Create a GitHub action to automatically update dependabot alerts

### ISSUE THREAD

**Issue by thinkbulecount2** [oaworks/oa-works#137]
We've been getting a lot of these Dependabot alerts lately and I'm wondering if we can implement this action to automatically update the versions on a weekly (daily?) basis.

Would love your output on this @sssoz and @JosephMcArthur!

Reference: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates

**Comment by sssoz** [comment]
OK to do this! Would be very useful. However, could you continue checking these automated updates to ensure everything looks good @thinkbulecount2?

Thank you.

**Comment by thinkbulecount2** [comment]
Yep, for sure @sssoz!

**Comment by sssoz** [comment]
Unassigning because this isn’t a priority for now. I’ve been taking care of the alerts.

**Comment by sssoz** [comment]
Probably not a good idea to automatically update this, closing
