### ISSUE TITLE
Update funders and libraries

### ISSUE THREAD

**Issue by sssoz** [oaworks/oa-works#149]
- [x] Add Gates to funders https://oa.works/about/
- [x] Add a place where we can put logos of libraries that’re paying to support our work (as with https://openaccessbutton.org/libraries). 
  - Can not be as prominent as Gates/Arcadia

@JosephMcArthur

**Comment by sssoz** [comment]
https://answers.netlify.com/t/support-guide-using-environment-variables-on-netlify-correctly/267

**Comment by JosephMcArthur** [comment]
Switching the repo used from oabutton/oaworks to oaworks/oaworks caused builds on dev to fail too.

Logs from before (https://app.netlify.com/sites/devoaworks/deploys/6321ee7e30d59b0e23607565) use `NPM version 6.14.4` while after (https://app.netlify.com/sites/devoaworks/deploys/6321f0d50c360b14d956ca28_ `NPM version 8.15.0`.

**Comment by sssoz** [comment]
Wrote to Netlify’s customer service about this. Here’s their response: 

> Hi Sophy,
> It seems that either you, or one of your dependencies is specifying a wrong version of something: https://app.netlify.com/sites/oaworks/deploys/632315f7b3636f328a11d142#L34. This is not like a Netlify problem, but something to check with your dependencies.

**Comment by sssoz** [comment]
Dev now works: https://dev.oa.works/people/

Somehow, the version number for Axios —which I had not changed— stopped working. I simply updated it. There are also a few high-severity vulnerabilities that I’ll be fixing while I’m here.

**Comment by sssoz** [comment]
@JosephMcArthur this task is now done on dev — see at the bottom of the "About" section: https://dev.oa.works/about/

Did you want a dedicated page to it? Asking because for now, we can also include this "funded by / supported by" section on any page we want so it's more visible

**Comment by sssoz** [comment]
Sure, I would propose to include that section on other pages for now though, for example at the bottom of every about and team pages!

**Comment by sssoz** [comment]
OK I’ve gone ahead and done that to give the funders more visibility: 

- https://dev.oa.works/products/
- https://dev.oa.works/about/vision/
- https://dev.oa.works/about/values/
- https://dev.oa.works/impact/

I quite like it there! Don’t forget we also have the "Covered in" block that we can do that with as well.

**Comment by sssoz** [comment]
Happy to merge to main / live site whenever.

**Comment by JosephMcArthur** [comment]
Can we remove from vision & values, but keep elsewhere –– then feel free to
push live!

Joe McArthur
Director / Co-Founder: OA.Works <https://oa.works>
The Open Access Button is now OA.Works! Find out more about our rebrand
<https://blog.oa.works/open-access-button-is-now-oa-works/>.

**Comment by sssoz** [comment]
Removed, done, and pushed to `main`. Should be on live in a few seconds. Closing this
