### ISSUE TITLE
add accessibility checking to build process

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/oa-works#34]
We want to set a high initial bar for accessiblity and know when we fall off track. One way to get this right day to day is by ensuring our build process is doing as many checks as possible for the simple stuff that can automated (or done manually once and monitored).

Some of this will be done via #32 as LH has many tests built in, however, if there are ways to go further that would be good.

Netlify has https://www.npmjs.com/package/netlify-plugin-a11y, which is built with https://pa11y.org/. However, I'm unsure how much further than Lighthouse it goes.

We could also have some tests run via Ghostinspector, depending on what they are.

Separately, it would be good to find (or write) a blogpost (detailing the tests that should be done manually & the suggested tools to do that) or service we could pay to manage tests that can't be automated periodically.

**Comment by sssoz** [comment]
It’s been added to GhostInspector.
