### ISSUE TITLE
Add more stories to stories page

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/oa-works#60]
We need to:

- [ ] decide which stories from [here](https://docs.google.com/spreadsheets/d/1sD6Y9uJCjgxp0IiUnBxXwJdzh-I3nUumaTQxiekVv8k/edit#gid=1098335235) are good enough to be put on the site. A nice mix of topics, styles, etc worked on would be great.

For as many was we can / think are great we should:

- [ ] find a good unsplash image https://unsplash.com/. Get a link to it, an attribution, and alt text.
- [ ] A word or two on what it's "for"

Those things could just be done in the sheet for now.

**Comment by JosephMcArthur** [comment]
TODO. One hour to get to 9 more. Likely don't go all the way to needing pagination or anything like that.

**Comment by jorlowitz** [comment]
Here are the 9 new stories with images and alt text.  They still need to be added to the json file: https://github.com/oaworks/oa-works/blob/main/src/_data/stories.json

**Comment by JosephMcArthur** [comment]
@sssoz can you check the alt-text here please?

**Comment by sssoz** [comment]
@JosephMcArthur I am adding in the image attributions and will be inputting them in the data file.

**Comment by sssoz** [comment]
Oh and the alt text is great!

**Comment by sssoz** [comment]
Done here https://oa.works/impact/stories/
and on the homepage.
