### ISSUE TITLE
Improve impact page

### ISSUE THREAD

**Issue by sssoz** [oaworks/oa-works#67]
- ~Animate numbers (count up)~
- [x] Link each card to a page 
> Stories shared -> oa.works/stories
Policies tracked-> SYP permissions (then OArights)
COVID papers -> RSCVD.org
OA searches -> Openaccessbutton.org
ILL searches -> instantILL.org
Guides -> For libraries page? (or should we make a guides resource page on new website)
Made open -> SYP?
Libraries use -> Testimonials?
Authors educated -> NOT SURE

**Comment by sssoz** [comment]
> Animate numbers (count up)

Seems a bit weird and a lot less impressive when the numbers aren’t actually accurate/precise & just an estimate.

**Comment by JosephMcArthur** [comment]
Yup. I think this can be closed without doing that. Being able to link each card to a page is a nice to have, but not important enough to do right now.

i.e I think this can be closed.

**Comment by sssoz** [comment]
Well I am doing that right now... that’s not a big deal. Just that the page doesn’t feel useful if it’s simply estimates of everything, feels a bit nebulous.

**Comment by sssoz** [comment]
On dev for your approval @JosephMcArthur : https://dev.oa.works/impact/ 

The bit that says "Many small changes add up to a more just system." doesn’t say much... Could we instead write something like "How we contribute to the Open Access movement  by the numbers"?
