### ISSUE TITLE
Make `main` a protected branch 

### ISSUE THREAD

**Issue by sssoz** [oaworks/oa-works#88]
@JosephMcArthur I might need access for that, or you might have to do it.

**Comment by JosephMcArthur** [comment]
LMK if you want settings adjusted. Also note double assignment on this issue.

![image](https://user-images.githubusercontent.com/4953703/116045176-b0a03b80-a669-11eb-8521-ece9b5a7a04f.png)

**Comment by sssoz** [comment]
looks good!
