### ISSUE TITLE
spacing issues on testimonial

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/oa-works#95]
@sssoz There's a misalignment in Peter Bae's testimonial (see bottom box and text overlap)

![image](https://user-images.githubusercontent.com/12050110/116157130-46a38880-a6a1-11eb-844e-90b71142baf6.png)

_Originally posted by @jorlowitz in https://github.com/oaworks/internal-planning/issues/109#issuecomment-827175971_

**Comment by sssoz** [comment]
Cards were not a good use case for the Partners and Testimonials pages. Using the same layout as the Team page now (full-width lists). 

Done: https://oa.works/people/partners/ & https://oa.works/impact/testimonials/
